version: "3"

services:
  hdmaster:
    image: nutthaphon/hadoop:3.1.2-spark-2.4.3
    container_name: hdmaster-test
    hostname: hdmaster
    working_dir: /admin-scripts
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
      - JAVA_HOME=${JAVA_HOME}
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
      - SPARK_HOME=${SPARK_HOME}
      - SPARK_JAR=hdfs://hdmaster:9000/user/spark/spark-jars.zip
      - LD_LIBRARY_PATH=${HADOOP_HOME}/lib/native
      - PYTHONPATH=${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.10.7-src.zip
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - PATH=$SPARK_HOME/python:${SPARK_HOME}/bin:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${JAVA_HOME}/bin:${PATH}
    ports:
      # SSH
      - "2220:22"
      # Hadoop Namenode Web
      - "9870:9870"
      # YARN Resource Manager
      - "8088:8088"
      # YARN Nodemanager Web UI
      - "8043:8042"
      # MapReduce JobHistory Server 
      - "19888:19888"
      # Spark Context Web UI
      - "4040:4040"
      # Spark History Server
      - "18080:18080"
      # Livy Spark Server
      - "8998:8998"
    volumes:
      - hadoop-etc:/hadoop/etc
      - hdmaster-dfs:/tmp/hadoop-hadoop
      - hdmaster-logs:/hadoop/logs
      - java-release:/java
      - livy-conf:/livy/conf
      - spark-conf:/spark/conf
      - admin-scripts:/admin-scripts
  
  hdslave1:
    image: nutthaphon/hadoop:3.1.2-spark-2.4.3
    container_name: hdslave1-test
    hostname: hdslave1
    working_dir: /hadoop/logs
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
      - JAVA_HOME=${JAVA_HOME}
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
      - SPARK_HOME=${SPARK_HOME}
      - SPARK_JAR=hdfs://hdmaster:9000/user/spark/spark-jars.zip
      - LD_LIBRARY_PATH=${HADOOP_HOME}/lib/native
      - PYTHONPATH=${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.10.7-src.zip
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - PATH=$SPARK_HOME/python:${SPARK_HOME}/bin:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${JAVA_HOME}/bin:${PATH}
    ports:
      # SSH
      - "2221:22"
      # YARN Nodemanager Web UI
      - "8044:8042"
      # Spark Context Web UI
      - "4041:4040"
    volumes:
      - hadoop-etc:/hadoop/etc
      - hdslave1-dfs:/tmp/hadoop-hadoop
      - hdslave1-logs:/hadoop/logs
      - java-release:/java
      - spark-conf:/spark/conf
      - admin-scripts:/admin-scripts
  
  hdslave2:
    image: nutthaphon/hadoop:3.1.2-spark-2.4.3
    container_name: hdslave2-test
    hostname: hdslave2
    working_dir: /hadoop/logs
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
      - JAVA_HOME=${JAVA_HOME}
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
      - SPARK_HOME=${SPARK_HOME}
      - SPARK_JAR=hdfs://hdmaster:9000/user/spark/spark-jars.zip
      - LD_LIBRARY_PATH=${HADOOP_HOME}/lib/native
      - PYTHONPATH=${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.10.7-src.zip
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - PATH=$SPARK_HOME/python:${SPARK_HOME}/bin:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${JAVA_HOME}/bin:${PATH}
    ports:
      # SSH
      - "2222:22"
      # YARN Nodemanager Web UI
      - "8045:8042"
      # Spark Context Web UI
      - "4042:4040"
    volumes:
      - hadoop-etc:/hadoop/etc
      - hdslave2-dfs:/tmp/hadoop-hadoop
      - hdslave2-logs:/hadoop/logs
      - java-release:/java
      - spark-conf:/spark/conf
      - admin-scripts:/admin-scripts

volumes:
  hadoop-etc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/share/etc
  hdmaster-dfs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdmaster/tmp
  hdslave1-dfs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave1/tmp
  hdslave2-dfs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave2/tmp
  hdmaster-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdmaster/logs
  hdslave1-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave1/logs
  hdslave2-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave2/logs
  java-release:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/java/latest
  livy-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/livy/share/conf
  spark-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/spark/share/conf
  admin-scripts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/scripts
