
services:

  hdmaster:
    image: nutthaphon/hadoop:3.1.3-spark-2.4.5
    container_name: hdmaster
    hostname: hdmaster
    working_dir: /scripts
    environment:
      - CLUSTER_NAME=hdcluster
      - JAVA_HOME=/java
      - HADOOP_HOME=/hadoop
      - HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
    ports:
      # SSH
      - "2220:22"
      # Hadoop Namenode Web
      - "9870:9870"
      # YARN Resource Manager
      - "8088:8088"
      # YARN Nodemanager Web UI
      - "8043:8042"
      # MapReduce JobHistory Server 
      - "19888:19888"
      # Spark Context Web UI
      - "4040:4040"
      # Spark History Server
      - "18080:18080"
      # Livy Spark Server
      - "8998:8998"
    volumes:
      - hadoop-etc:/hadoop/etc
      - hdmaster-dfs:/tmp/hadoop-hadoop
      - hdmaster-logs:/hadoop/logs
      - java-home:/java
      - admin-scripts:/scripts

  hdslave1:
    image: nutthaphon/hadoop:3.1.3-spark-2.4.5
    container_name: hdslave1
    hostname: hdslave1
    working_dir: /scripts
    environment:
      - CLUSTER_NAME=hdcluster
      - JAVA_HOME=/java
      - HADOOP_HOME=/hadoop
      - HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
    ports:
      # SSH
      - "2221:22"
      # YARN Nodemanager Web UI
      - "8044:8042"
      # Spark Context Web UI
      - "4041:4040"
    volumes:
      - hadoop-etc:/hadoop/etc
      - hdslave1-dfs:/tmp/hadoop-hadoop
      - hdslave1-logs:/hadoop/logs
      - java-home:/java
      - admin-scripts:/scripts

  
  hdslave2:
    image: nutthaphon/hadoop:3.1.3-spark-2.4.5
    container_name: hdslave2
    hostname: hdslave2
    working_dir: /scripts
    environment:
      - CLUSTER_NAME=hdcluster
      - JAVA_HOME=/java
      - HADOOP_HOME=/hadoop
      - HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
    ports:
      # SSH
      - "2222:22"
      # YARN Nodemanager Web UI
      - "8045:8042"
      # Spark Context Web UI
      - "4042:4040"
    volumes:
      - hadoop-etc:/hadoop/etc
      - hdslave2-dfs:/tmp/hadoop-hadoop
      - hdslave2-logs:/hadoop/logs
      - java-home:/java
      - admin-scripts:/scripts

volumes:
  hadoop-etc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/share/etc
  hdmaster-dfs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdmaster/tmp
  hdslave1-dfs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave1/tmp
  hdslave2-dfs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave2/tmp
  hdmaster-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdmaster/logs
  hdslave1-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave1/logs
  hdslave2-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop/nodes/hdslave2/logs
  java-home:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/java/jdk1.8.0_241
  admin-scripts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/scripts
