version: "3"

services:
  hdmaster:
    image: nutthaphon/hadoop-master:3.1.2-spark2.4.3-jdk8
    container_name: hdmaster
    hostname: hdmaster
    working_dir: "/spark"
    #user: "1000:1000"
    #stdin_open: true
    #tty: true
    environment:
      - CLUSTER_NAME=poc
    ports:
      # SSH
      - "2220:22"
      # Hadoop Namenode Web
      - "9870:9870"
      # Hadoop Datanode Web
      #- "9864:9864"
      # YARN Resource Manager
      - "8088:8088"
      # MapReduce JobHistory Server 
      - "19888:19888"
      # Spark Context Web UI
      - "4040:4040"
      # Spark History Server
      - "18080:18080"
      # Livy Spark Server
      - "8998:8998"
    volumes:
      - hdmaster-hadoop:/hadoop
      - java-program:/java
      - spark-program:/spark
      - livy-spark:/livy
      - pig-program:/pig
  
  hdslave1:
    image: nutthaphon/hadoop-slave1:3.1.2-spark2.4.3-jdk8
    container_name: hdslave1
    hostname: hdslave1
    working_dir: "/spark"
    #user: "1000:1000"
    #stdin_open: true
    #tty: true
    ports:
      # SSH
      - "2221:22"
      # Hadoop Datanode Web
      #- "9864:9864"
      # Spark Context Web UI
      - "4041:4040"
      # Node Manager
    volumes:
      - hdslave1-hadoop:/hadoop
      - java-program:/java
      - spark-program:/spark

  hdslave2:
    image: nutthaphon/hadoop-slave2:3.1.2-spark2.4.3-jdk8
    container_name: hdslave2
    hostname: hdslave2
    working_dir: "/spark"
    #user: "1000:1000"
    #stdin_open: true
    #tty: true
    ports:
      # SSH
      - "2222:22"
      # Hadoop Datanode Web
      #- "9864:9864"
      # Spark Context Web UI
      - "4042:4040"
      # Node Manager
    volumes:
      - hdslave2-hadoop:/hadoop
      - java-program:/java
      - spark-program:/spark
  
  hiveserver2:
    image: nutthaphon/hive2:3.1.1-jdk8
    container_name: hiveserver2
    hostname: hiveserver2
    working_dir: "/program/hive"
    stdin_open: true
    tty: true
    ports:
      # SSH
      - "2224:22"
      # Derby
      - "1527:1527"
      # Thrift RPC
      - "10000:10000"
      # Thrift HTTP
      - "10001:10001"
      # HiveServer2 web
      - "10002:10002"
    volumes: 
      - hdmaster-hadoop:/hadoop
      - java-program:/java
      - bigdata-program:/program

  nifiserver:
    image: nutthaphon/nifi:1.9.2-jdk8
    #restart: always
    entrypoint: "bash -c"
    command: "exit 0"
    container_name: nifiserver
    hostname: nifiserver
    working_dir: "/program/nifi/nifi-1.9.2"
    #stdin_open: true
    #tty: true
    ports:
      # SSH
      - "2225:22"
      # HTTP
      - "8080:8080"
      # HTTPS
      - "9443:9443"
      # Remote Input Socket
      - "10443:10443"
    volumes:  
      - bigdata-program:/program

  zeppelin:
    image: nutthaphon/zeppelin:0.8.1-sshd
    #restart: always
    entrypoint: "bash -c"
    command: "exit 0"
    container_name: zeppelin
    hostname: zeppelin
    #working_dir: "/zeppelin"
    #stdin_open: true
    #tty: true
    environment:
      - ZEPPELIN_NOTEBOOK_DIR=/workspace/notebook
      - ZEPPELIN_LOG_DIR=/workspace/logs
    ports:
      # SSH
      - "2226:22"
      # HTTP
      - "9080:8080"
    volumes:  
      - zeppelin-workspace:/workspace
      - hdmaster-hadoop:/hadoop
      - java-program:/java
      - spark-program:/spark
  
  mongodb:
    image: nutthaphon/mongo:4.0.10
    command: --bind_ip 0.0.0.0
    #restart: always
    entrypoint: "bash -c"
    command: "exit 0"
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd1
    ports:
      # MongoDB listening port
      - "27017:27017"
    
    volumes:
      - mongo-data:/data/db
      #- mongo-conf:/etc/mongo
  
  columnstore:
    image: nutthaphon/mariadb-columnstore:1.2.3
    #restart: always
    entrypoint: "bash -c"
    command: "exit 0"
    container_name: columnstore
    hostname: columnstore
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw0rd1
    ports:
      # MariaDB listening port
      - "3306:3306"
    volumes:
      - mariadb-etc:/usr/local/mariadb/columnstore/etc
      - mariadb-data1:/usr/local/mariadb/columnstore/data1
      - mariadb-local:/usr/local/mariadb/columnstore/local
      - mariadb-mysql-db:/usr/local/mariadb/columnstore/mysql/db

  mysql:
    image: nutthaphon/mariadb:10.4.6
    command: --character-set-server=tis620 --collation-server=tis620_thai_ci
    #restart: always
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd1
    ports:
      # Mysql listening port
      - "13306:3306"
    volumes:
      - mysql-data1:/var/lib/mysql
      - mysql-conf:/etc/mysql/conf.d

  hueserver:
    image: nutthaphon/hue:4.4.0
    depends_on:
      - mysql
      - hiveserver2
    #restart: always
    #stdin_open: true
    #tty: true
    container_name: hueserver
    hostname: hueserver
    ports:
      # Web listening port
      - "8888:8888"
    volumes:
      - hdmaster-hadoop:/hadoop
      - /home/nutt/Docker/bigdata/hue/conf/hue.ini:/usr/share/hue/desktop/conf/hue.ini

  oozie:
    image: nutthaphon/oozie:5.1.0
    working_dir: "/oozie"
    #restart: always
    #stdin_open: true
    #tty: true
    container_name: oozie
    hostname: oozie
    ports:
      # Oozie Web console
      - "11000:11000"
    volumes:
      - hdmaster-hadoop:/hadoop
      - oozie-program:/oozie
      - pig-program:/pig
      - java-program:/java

volumes:
  mysql-data1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mariadb/mysql/data1
  mysql-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mariadb/mysql/conf
  mariadb-etc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mariadb/columnstore/etc
  mariadb-data1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mariadb/columnstore/data1
  mariadb-local:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mariadb/columnstore/local
  mariadb-mysql-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mariadb/columnstore/mysql/db
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mongo/data
  mongo-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/mongo/conf
  bigdata-program:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata
  zeppelin-program:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/zeppelin/0.8.1
  zeppelin-workspace:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/zeppelin/workspace
  java-program:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/java/jdk1.8.0_211
  spark-program:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/spark/spark-2.4.3-bin-hadoop2.7
  livy-spark:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/spark/apache-livy-0.6.0-incubating-bin
  hdmaster-hadoop:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop-3.1.2-cluster/hdmaster
  hdslave1-hadoop:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop-3.1.2-cluster/hdslave1
  hdslave2-hadoop:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/hadoop-3.1.2-cluster/hdslave2
  oozie-program:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/oozie/oozie-5.1.0
  pig-program:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/pig/pig-0.17.0
  maven-program:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/Docker/bigdata/maven/apache-maven-3.6.1
  maven-repo:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nutt/.m2